site_name: VKWave
site_description: 'Документация фреймворка VKWave'
site_author: 'FSC Dev'
repo_name: 'fscdev/vkwave'
repo_url: 'https://github.com/fscdev/vkwave'

copyright: '2020-2021 FSC Dev & VkWave Contributors'

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
  font:
    code: Fira Code
  language: ru
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - instant
    - tabs
  icon:
    repo: fontawesome/brands/github

extra:
  version: 0.2.10
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/vkwave
      name: 'Чат в Telegram'
  alternate:
    - name: English (in progress)
      link: https://fscdev.github.io/vkwave/en
      lang: en

    - name: Русский
      link: https://fscdev.github.io/vkwave/ru
      lang: ru

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
  - markdown_include.include:
      base_path: docs

nav:
  - Главная: ru/index.md
  - Начало работы:
    - ru/getting_started/index.md
    - ru/getting_started/echo.md
    - Фильтры:
      - ru/getting_started/filters/index.md
      - ru/getting_started/filters/builtin.md
      - ru/getting_started/filters/combining.md
      - ru/getting_started/filters/custom.md
    - ru/getting_started/multitoken.md
    - ru/getting_started/clones.md
    - ru/getting_started/keyboards.md
    - ru/getting_started/templates.md
    - ru/getting_started/uploaders.md
    - ru/getting_started/routers.md
    - ru/getting_started/middleware.md
  - Client:
    - ru/client/index.md
    - ru/client/context.md
    - ru/client/using.md
    - ru/client/custom.md
  - API:
    - ru/api/index.md
  - Bots:
    - ru/bots/index.md
    - ru/bots/easy.md
    - ru/bots/usage.md
    - ru/bots/filters.md
    - ru/bots/routers.md
    - ru/bots/fsm.md
    - ru/bots/storage.md
    - Utils:
        - ru/bots/utils/index.md
        - ru/bots/utils/keyboard.md
        - ru/bots/utils/templates.md
        - ru/bots/utils/uploaders.md
  - LongPoll:
    - ru/longpoll/index.md
  - Types:
    - ru/types/index.md
  - HTTP:
    - ru/http/index.md
